include:
  - project: "devops-team/ci-templates"
    ref: main
    file:
      - /terraform/.terraform.yml

stages:
  - prepare
  - validate
  - build
  - deploy

init:
  extends: .init

validate:
  extends: .validate

plan:
  extends: .plan

apply:
  extends: .apply

workflow:
  rules:
    - when: always
    - changes:
        - "*.md"
      when: never
