repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: local
    hooks:
      - id: jira-ticket
        name: check for jira ticket
        language: pygrep
        entry: '\A(?!JIRA-[0-9]+)'
        args: [--negate]
        stages: [commit-msg]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_trivy
      - id: terraform_checkov
      - id: terraform_validate
      - id: tfupdate
      - id: terraform_wrapper_module_for_each
